# Generated by Django 4.2.1 on 2023-05-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgety', '0003_remove_profile_username_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address2',
            new_name='Bank_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='Branch',
        ),
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.FloatField(default=50),
        ),
    ]
