# Generated by Django 4.2.1 on 2023-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgety', '0004_rename_address2_profile_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bvn',
            field=models.FloatField(default=50),
        ),
    ]
