# Generated by Django 4.2.1 on 2023-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
